---

- name: install pre-requisite packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - sssd

- name: add sssd configuration file
  template:
   src: sssd.conf.j2
   dest: /etc/sssd/sssd.conf
   owner: root
   group: root
   mode: 0600

- name: add ldap public certificate
  template:
   src: ldap.crt.j2
   dest: /usr/share/ca-certificates/ldap.crt
   owner: root
   group: root
   mode: 0611

- name: add sshd configuration file
  template:
   src: sshd_config.j2
   dest: /etc/ssh/sshd_config
   owner: root
   group: root
   mode: 0611

- name: add sudoers file
  template:
   src: 50-sssd.j2
   dest: /etc/sudoers.d/50-sssd
   owner: root
   group: root
   mode: 0611

- name: add pam.d config file
  template:
   src: systemd-user.j2
   dest: /etc/pam.d/systemd-user
   owner: root
   group: root
   mode: 0611

# /etc/nsswitch.conf
#
# /etc/ssh/sshd_config

- name: Enable sssd
  service:
    name: sssd
    state: started
    enabled: yes

- name: Enable sshd
  service:
    name: sshd
    state: restarted
    enabled: yes
