---

- name: install pre-requisite packages
  apt:
    name: {{item}}
  vars:
    packages:
    - sssd

- name: add sssd configuration file
  template:
   src: sssd.conf.j2
   dest: /etc/sssd/sssd.conf
   owner: root
   group: root
   mode: 0600

- name: add ldap public certificate
  template:
   src: ldap.crt.j2
   dest: /usr/share/ca-certificates/ldap.crt
   owner: root
   group: root
   mode: 0660


# /etc/nsswitch.conf
#
# /etc/ssh/sshd_config

- name: Enable sssd
  service:
    name: sssd
    state: started
    enabled: yes

- name: Enable sshd
  service:
    name: sshd
    state: restarted
    enabled: yes
